packer
Otus-DevOps-22-08/antonbzbzz_infra pull request #2
Opened 2022-10-27 06:20 UTC by antonbzbzz

Добрый день!
Добавлен шаблон для создания образа (ubuntu16.json) и параметризированные опции в файл variables.json.examples.

2022-10-27 08:05 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно добавить фейковый ключ для доступа к облаку
И в переменной указать где он находится
ДЗ возвращаю на доработку

2022-10-28 14:20 UTC, mrgreyves approved these changes
Вот теперь все круто =)

2022-10-29 19:22 UTC, antonbzbzz commented
Спасибо!)

2022-10-29 19:28 UTC, antonbzbzz commented
случайно закрыл

2022-10-29 19:39 UTC, merged